import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

// Lê o .env.local (se existir, senão .env)
const envLocalPath = path.join(rootDir, '.env.local');
const envPath = path.join(rootDir, '.env');
const targetEnvFile = fs.existsSync(envLocalPath) ? envLocalPath : envPath;

if (fs.existsSync(targetEnvFile)) {
    dotenv.config({ path: targetEnvFile });
    console.log(`[Env] Loaded environment from ${path.basename(targetEnvFile)}`);
} else {
    console.warn('[Env] No .env.local or .env file found. Falling back to process.env');
}

const envObject = {
    FIREBASE_API_KEY: process.env.FIREBASE_API_KEY || "",
    FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN || "barcl-6e65e.firebaseapp.com",
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID || "barcl-6e65e",
    FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET || "barcl-6e65e.appspot.com",
    FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID || "",
    FIREBASE_APP_ID: process.env.FIREBASE_APP_ID || ""
};

const outputContent = `// SYSTEM AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Generated by scripts/generate-env.js
window.__BARCL_ENV__ = ${JSON.stringify(envObject, null, 4)};
`;

const outputPath = path.join(rootDir, 'runtime-env.js');
fs.writeFileSync(outputPath, outputContent);

console.log(`[Env] Successfully generated runtime-env.js with ${Object.keys(envObject).length} variables.`);
